### ISSUE TITLE
Specifying RELEASE as the camunda version creates a dependency to a non-existent artifact

### ISSUE THREAD

**Issue by brentfisher-taulia** [camunda/camunda-bpm-process-test-coverage#15]
The pom generated for this library creates a dependency in the pom like this:
```
   <dependencies>
        <dependency>
            <groupId>org.camunda.bpm</groupId>
            <artifactId>camunda-engine</artifactId>
            <version>RELEASE</version> <!-- We intentionally always compile against RELEASE, but
                                            test against many versions *provided* by user projects.
                                            Therefore the tests are in a separate module. -->
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.camunda.bpm</groupId>
            <artifactId>camunda-engine-spring</artifactId>
            <version>RELEASE</version> <!-- We intentionally always compile against RELEASE, but
                                            test against many versions *provided* by user projects.
                                            Therefore the tests are in a separate module. -->
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

Unfortunately, in looking through maven central, this version doesn't exist and the old way of using RELEASE for the latest artifact was deprecated years ago.

Is there another way to do this?

**Comment by martinschimak** [comment]
Thank you for pointing this out. 

As on one hand, Maven 3 still supports this and on the other hand it is just a "provided" dependency, it should in principle do no harm for the foreseeable future... did you experience issues in a specific context? Or do you just point out the fact of deprecation? 

Anyway, I changed these dependencies on master now to specific versions and therefore close this issue. Thank you!
