### ISSUE TITLE
Explanation on how this works?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-bpm-process-test-coverage#28]
Can a explanation be provided about how this works?  Something like a few sentences that explain the technical process followed to produce the output?

**Comment by janinawiegers** [comment]
I attach a sample test which I got from camunda training. It generates html files within your project folder `/target/process-test-coverage` with an overlay of which process parts were unit tested.

**Comment by janinawiegers** [comment]
```
public class SampleTest {

	private ProcessInstance processInstance;

	@ClassRule
	@Rule
	public static ProcessEngineRule rule = TestCoverageProcessEngineRuleBuilder.create().build();

	@Before
	public void before() {

		init(rule.getProcessEngine());

		processInstance = processEngine().getRuntimeService()
				.startProcessInstanceByKey("sample");

	}

	@Test
	@Deployment(resources = "myprocess.bpmn")
	public void shouldPassSubprocess() {
		//run through your process here

	}
}
```

**Comment by StephenOTT** [comment]
Yes. Sorry, I meant what is the underlying logic in the code that creates the HTML

**Comment by StephenOTT** [comment]
found: https://github.com/camunda/camunda-bpm-process-test-coverage/blob/master/IMPLEMENTATION.md
