### ISSUE TITLE
create complete test report failed

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-bpm-process-test-coverage#5]
Currently you can't see the test report on a windows computer:

```
Okt 05, 2016 1:15:33 PM org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil installBowerComponents
SCHWERWIEGEND: Unable to copy bower_components!
java.lang.IllegalArgumentException: URI is not hierarchical
    at java.io.File.<init>(File.java:418)
    at org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil.installBowerComponents(CoverageReportUtil.java:176)
...
```

The directory separator should be File.separator;

**Comment by ingorichtsmeier** [comment]
Ok, after some tries it seems that this line didn't work if you use the library from your maven repository:

CoverageReportUtil.java:176

The library is unable to select the bower package in the jar file. Maybe this discussion leads to a solution: http://stackoverflow.com/questions/18055189/why-my-uri-is-not-hierarchical

Cheers, Ingo

**Comment by martinschimak** [comment]
Helli Ingo - very important feedback, thank you!

**Comment by berndruecker** [comment]
We recently got another error with the test coverage on our Jenkins. Sounds related?

11:39:58 testHellManuelleVerarbeitung(com.camunda.demo.versicherungsneuantrag.NeuantragProcessTest)  Time elapsed: 1.206 sec  <<< ERROR!
11:39:58 java.lang.NullPointerException
11:39:58 	at org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil.installBowerComponents(CoverageReportUtil.java:139)
11:39:58 	at org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil.createReport(CoverageReportUtil.java:79)
11:39:58 	at org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil.createCurrentTestMethodReport(CoverageReportUtil.java:64)
11:39:58 	at org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule.handleTestMethodCoverage(TestCoverageProcessEngineRule.java:286)
11:39:58 	at org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule.finished(TestCoverageProcessEngineRule.java:122)
11:39:58 	at org.junit.rules.TestWatcher.finishedQuietly(TestWatcher.java:111)

**Comment by martinschimak** [comment]
Hi @ingorichtsmeier @berndruecker I looked into this issue and my best guess for both of them is that we need to make the lookup of the jar file location more robust. As I cannot however reproduce your issues (also not on windows), I want to ask you whether you could give this branch https://github.com/camunda/camunda-bpm-process-test-coverage/tree/feat/install-bower-components a try within your environments. I am quite confident that I have fixed @berndruecker 's NullPointerException, I am just 50/50 confident that @ingorichtsmeier 's issue.

**Comment by ingorichtsmeier** [comment]
Hi @martinschimak, 

the root cuase is most likely the space in my user directory name. So the component fails to export the bower directory of a jar located C:\Users\Ingo Richtsmeier\.m2\repository\org\camunda\bpm\extension\camunda-bpm-process-test-coverage\0.2.8\camunda-bpm-process-test-coverage-0.2.8.jar. I've set my repo in the settings.xml with
`<localRepository>c:\maven-repo\repository</localRepository>`
to a directory name without spaces and everything works fine.

So you should be able to force the error in a maven setting using a repository path with a space.

**Comment by ingorichtsmeier** [comment]
OK, I've found a hint: If you have a directory with a space, "First Last", the URI is "First%20Last". Afterwords the code checks in [line 145](https://github.com/camunda/camunda-bpm-process-test-coverage/blob/master/core/src/main/java/org/camunda/bpm/extension/process_test_coverage/util/CoverageReportUtil.java#L145 ) if this is a file. The operating system returns false, so would not look into the jar.

If I replace the "%20" with a space, the .isFile() returns true.

**Comment by ingorichtsmeier** [comment]
See [this pull request](https://github.com/camunda/camunda-bpm-process-test-coverage/pull/12) to solve the problem (at least for me).

**Comment by martinschimak** [comment]
Hi @ingorichtsmeier many thx for pointing out the underlying reason for your problem and even providing a pr. However, based on your insights I can now reproduce your error report and can also reproduce that my last week's investment into robustness (the feat/bower-install-components) branch mentioned above) fixes that error, too. I will therefore close #12! But many thx!!
