### ISSUE TITLE
Consider to add three main OS platforms to CI test matrix

### ISSUE THREAD

**Issue by martinschimak** [camunda/camunda-bpm-process-test-coverage#6]

**Comment by martinschimak** [comment]
Won't fix, because Travis CI currently does not support Windows. We have however now a working local development environment under Windows, too. I consider it not important enough to test OSX separately from Linus via Travis CI until proven wrong. I will therefore close this issue.

**Comment by zambrovski** [comment]
It does work in GH actions.
