### ISSUE TITLE
Release project under 0.4.0

### ISSUE THREAD

**Issue by zambrovski** [camunda/camunda-bpm-process-test-coverage#63]
Hi folks,

I wondered that the project looks a little abandoned. 
Who is the Camunda "project supporter"?

I'm would like to get some feedback from active developers / supporters and synchronize activities with them.

I cleaned up the issues, closed most PRs and open discussions pretending bugs (could not reproduce anymore or it is a missing feature but not a bug).

Cheers,

Simon

**Comment by zambrovski** [comment]
@falko or @berndruecker do you know who is the Camunda "supporter" behind this project?

**Comment by berndruecker** [comment]
Hey Simon. Great to hear - thanks for your effort! Actually, I currently don't know of any supporter within Camunda, maybe Falko still dedicates the most love to it - but has a lot of other priorities. Also the process might have changed - @NPDeehan could probably comment on this.

**Comment by zambrovski** [comment]
My special interest in this question is, who from Camunda can decide about the release and who pushes the "produce release" button. So to me, I would like to release the current version of the repository as a maintenance / bugfix release before we start with a bigger rebuild of separation of collection from report generation (and address issues like #29)

**Comment by berndruecker** [comment]
Ah - ok. So if you say the stuff is ready to be released let me figure out how we organize the release (or push the button myself if I find it ;-))

**Comment by berndruecker** [comment]
Found the right Jenkins job - so I can trigger releases. What version to you want the release to have @zambrovski ?

**Comment by berndruecker** [comment]
Remembering the Jenkins URL here so I can close all tabs till Simon comes back :-)
https://ci.consulting.camunda.cloud/job/community-extension-process-test-coverage-DISTRO-RELEASE/release/

**Comment by zambrovski** [comment]
Please produce 0.4.0 release.

**Comment by berndruecker** [comment]
OK - I am on it. Problem with the infrastructure which we need to resolve first. I will come back to you later today or tomorrow

**Comment by berndruecker** [comment]
required https://github.com/camunda/camunda-bpm-process-test-coverage/issues/78

**Comment by berndruecker** [comment]
Job is here: https://ci.consulting.camunda.cloud/job/camunda/job/camunda-bpm-process-test-coverage/job/master/

**Comment by berndruecker** [comment]
@zambrovski Getting there. One other last riddle to solve ;-)

**Comment by berndruecker** [comment]
Available on Maven Central
