### ISSUE TITLE
Compile against 7.6.0 alpha fails

### ISSUE THREAD

**Issue by lldata** [camunda/camunda-bpm-process-test-coverage#8]
In TestCoverageProcessEngineRule.java:

CompensationEventHandler.EVENT_HANDLER_TYPE seems to be removed in 7.6.x
I can't figure out what to replace it with.

**Comment by martinschimak** [comment]
Thank you for reporting this. I actually already was aware that we will need to look into this - as soon as somebody finds some time to fix it :-) Speaking of time: eventually you find time to configure the library as shown here: https://github.com/camunda/camunda-bpm-process-test-coverage/blob/master/test/src/test/resources/camunda.cfg.xml and to comment the compensation handler. Can you confirm that the (precompiled) library then still "works"? (The downside of not using the compensation handler in my understanding is just that triggered compensation events are not shown as "green", but the attached compensation activities still are!)
