### ISSUE TITLE
Enable coverage from Spring driven tests

### ISSUE THREAD

**Issue by lldata** [camunda/camunda-bpm-process-test-coverage#9]
I'd like to be able to configure the process engine with Spring and override the default behavior of bootstrapping camunda from the camunda.cfg.xml file.

**Comment by martinschimak** [comment]
Many thx @lldata for this improvement. Apologies that it took somewhat longer than it should to appreciate it publicly! 👍 (This issue closes together with #10)

**Comment by martinschimak** [comment]
The spring style of initialising a process test coverage rule seems to be problematic, because as a consequence, the coverage report on a class level is missing. I opened #16 and would appreciate any observations and/or feedback on this. Maybe I am just missing something?
